package com.detection.platform.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * 网站分析实体类
 * 
 * @author Detection Platform
 * @since 2024-11-12
 */
@Data
@TableName("t_website_analysis")
public class WebsiteAnalysis {

    /**
     * 主键ID
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 分析类型: AUTO_REGISTER(自动化注册), NUMBER_CHECK(号码检测)
     */
    private String analysisType;

    /**
     * 网站名称
     */
    private String websiteName;

    /**
     * 网站地址
     */
    private String websiteUrl;

    /**
     * 分析状态: 1-分析中, 2-已完成, 3-失败
     */
    private Integer analysisStatus;

    /**
     * 注册接口
     */
    private String registerApi;

    /**
     * 注册方法
     */
    private String registerMethod;

    /**
     * 检测到的加密类型
     */
    private String encryptionType;

    /**
     * RSA密钥接口
     */
    private String rsaKeyApi;

    /**
     * 分析得到的请求头(JSON)
     */
    private String requestHeaders;

    /**
     * 必填字段列表(JSON)
     */
    private String requiredFields;

    /**
     * 推荐的执行器ID
     */
    private Long suggestedExecutorId;

    /**
     * 自动生成的执行脚本
     */
    private String autoGeneratedScript;

    /**
     * 检测接口
     */
    private String checkApi;

    /**
     * 检测方法
     */
    private String checkMethod;

    /**
     * 分析结果(JSON)
     */
    private String analysisResult;

    /**
     * 错误信息
     */
    private String errorMessage;

    /**
     * 创建时间
     */
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;

    /**
     * 完成时间
     */
    private LocalDateTime completeTime;

    /**
     * 逻辑删除
     */
    @TableLogic
    private Integer deleted;
}
